# .travis.yml
dist: trusty

sudo: required

language: python
python: 2.7

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: pypy
          env: TOXENV=pypy

before_install: 'pip install --upgrade pip'

install: 'pip install tox'

script:
    - 'tox'

